### ISSUE TITLE
Distributed training

### ISSUE THREAD

**Issue by Thol1998** [d1024choi/HLSTrajForecast#3]
Hello I want to ask a question about distributed training,I use 'bash argoverse_train.sh' to train, but I didn't find args.multi_gpu in the code, so I want to know how to use distributed training.

    Thanks!

**Comment by d1024choi** [comment]
The distributed training activated by "args.multi_gpu" is deprecated in this version. Please ignore it!

**Comment by Thol1998** [comment]
That is to say, the code does not support distributed training，right?

Thanks!

**Comment by d1024choi** [comment]
Unfortunately, Yes! 

The distributed training was used for our initial model dealing with HDmap images. Our final model does not use HDmap images anymore. Thank you for your comment :)
